notifications:
  email:
    - kwoolery@gmail.com

sudo: true
dist: trusty
language: generic
install:
- sudo pip -q install -r requirements.txt

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
